### ISSUE TITLE
Base path of templates always added to the output path? [$50]

### ISSUE THREAD

**Issue by saschakreher** [chenasraf/simple-scaffold#44]
**Describe the bug**
Accordingly to the documentation, I expect the folder structure within the templates path to be recreated within the output path. 
Butt currently it seems like the base path of the template folder is also always added to the output. 

**To Reproduce**

Prepare folder structure: 
C:\somewhere
C:\somewhere\foo
C:\somewhere\foo\templates
C:\somewhere\foo\templates\\{{Name}}.txt
C:\somewhere\foo\templates\sub
C:\somewhere\foo\templates\sub\\{{Name}}.txt

Execute:
npx simple-scaffold -t ./foo/templates -o ./output MyComponent

Output is
C:\somewhere\output\foo\templates\MyComponent.txt
C:\somewhere\output\foo\templates\sub\subMyComponent.txt

**Expected behavior**
C:\somewhere\output\MyComponent.txt
C:\somewhere\output\sub\MyComponent.txt

I expect the folder structure within the template path to be recreated in the output folder. But not the template base path.

**Desktop (please complete the following information):**
- OS: Windows 10
- Node.js: 14.15.4
- Simple Scaffold Version 1.1.2

**Comment by chenasraf** [comment]
Hi @saschakreher, thanks for the report! Sorry to see you are having issues.

To help me debug, can you answer a few questions?

- In the command example you specified, you are using forward slashes. Does this reflect what you used in reality, or only in the example here?
  - If that's what you used initially, can you tell me if replacing the slashes changes anything?
- Does adding a glob to the template change anything? For example, changing the template arg to `.\foo\templates\**\*`

In the meantime I will do some testing, these questions will help me pinpoint whether the bug is with Windows compatibility, or with the general template processing flow.

**Comment by chenasraf** [comment]
I believe this should actually be fixed, I should transform the paths in each input to the correct OS to make sure there are no problems like this. For example a lot of scripts in projects could be made for UNIX by default and just happen to be cloned on a Windows box. Shouldn't make a difference to the script.

Thanks for catching this! I will add some fixes and tests and will close this when they are ready.

**Comment by chenasraf** [comment]
@saschakreher I have published a pre-release version `v1.1.3-pre.2` (#45), I believe the fix there should fix both issues - the backslash being required, and the path being appended incorrectly. Can you verify this working? If so I will publish a full version.

Thanks!

**Comment by saschakreher** [comment]
Checked the v1.1.3-pre.2 but it seems like the behavior is the same. 

**Case 1**
Glob template path with slashes is always added to the output path
```
C:\somewhere>npx simple-scaffold -t ./foo/templates/**/* -o ./output MyComponent

Writing to C:\somewhere\output\foo\templates\MyComponent.txt
Writing to C:\somewhere\output\foo\templates\sub\subMyComponent.txt
```

**Case 2**
Non-Glob template path with slashes is always added to the output path
```
C:\somewhere>npx simple-scaffold -t ./foo/templates -o ./output MyComponent

Writing to C:\somewhere\output\foo\templates\MyComponent.txt
Writing to C:\somewhere\output\foo\templates\sub\subMyComponent.txt
```

**Case 3**
Glob template path with backslashes is not added to the output path <-- _what I expect_
```
C:\somewhere>npx simple-scaffold -t .\foo\templates\**\* -o .\output MyComponent

Writing to C:\somewhere\output\MyComponent.txt
Writing to C:\somewhere\output\sub\subMyComponent.txt
```
**Case 4**
Non glob template path with backlashes is added to the output path. <-- _still not sure if that's intended._
```
C:\somewhere>npx simple-scaffold -t .\foo\templates -o .\output MyComponent

Writing to C:\somewhere\output\foo\templates\MyComponent.txt
Writing to C:\somewhere\output\foo\templates\sub\subMyComponent.txt
```

**Comment by chenasraf** [comment]
@saschakreher That's too bad. Thank you very much for the detailed reply. I will make sure to make better tests and solve this problem. Might take another day or two, so I apologize in advance for the wait :)

**Comment by chenasraf** [comment]
I haven't forgotten about this, it's just difficult to get all the tests to work properly on Windows, I might have to re-think some of the path generation code. Sorry for the delay.

**Comment by chenasraf** [comment]
[Posted a bounty](https://app.bountysource.com/issues/117463371-base-path-of-templates-always-added-to-the-output-path) to get help with this as I'm not very familiar with NPM/Windows paths, and would love extra eyes on this.

**Comment by locene** [comment]
Print the `nonGlobTemplate` (which in the `getTemplateGlobInfo` method):

`-t ./foo/templates -o ./output`
nonGlobTemplate: `./foo/templates`

`-t ./foo/templates/**/* -o ./output`
nonGlobTemplate: `./foo/templates\`

`-t .\foo\templates -o .\output`
nonGlobTemplate: `.\foo\templates`

`-t .\foo\templates\**\* -o .\output`
nonGlobTemplate: `.\foo\templates\`

As you can see, the result is different, so you need to normalize it. Note that we do not need to use the custom `pathFix` method here, as there is a ready-made function available at: https://nodejs.org/api/path.html#pathnormalizepath

Additionally, it is not recommended to use `**/*` in path, because it behaves differently on Windows and Linux.

PR #48
