### ISSUE TITLE
[FEATURE] Easier way to pass key=value pairs as data to templates

### ISSUE THREAD

**Issue by nirajsavaika** [chenasraf/simple-scaffold#51]
#### Is your feature request related to a problem? Please describe.

Hello, thanks for creating and maintaining this library. Currently I am primarily using it through CLI and for most of my templates the data will be a small set of key-value pairs. However writing json in terminal is somewhat cumbersome as we have to deal with braces, quoting etc.

#### Describe the solution you'd like

It would be convenient if we could pass key=value pairs directly to the cli similar to how httpie autoconverts key=value pairs to json ([Reference](https://httpie.io/docs/cli/nested-json)).

So,  instead of: 

```
npx simple-scaffold MyComponent \
    -t project/scaffold/**/* \
    -o src/components \
    -d '{"className": "myClassName","author": "Chen Asraf"}'
    MyComponent
```

we would be able to write

```
npx simple-scaffold MyComponent \
    -t project/scaffold/**/* \
    -o src/components \
    MyComponent className=myClassName author="Chen Asraf"
```

which is easier to type. For non-strings httpie supports `:=` which is also convenient.

**Comment by chenasraf** [comment]
This actually used to be the way before v1. I originally switched to JSON as it is easier to use any tool or language for the data as it is more universal, while the `key=value` way was a bit less convenient for generated command outputs.

I am considering bringing this alternative back as a solution. Maybe with an uppercase `-D` flag? I will try to see if it makes sense to implement 2 forms for the same command. What happens when you use both? Do they get merged? etc.

Thanks for the suggestions :) will try some things out and update here

**Comment by chenasraf** [comment]
@nirajsavaika Hi, 

I have just release version 1.2.0.

You should be able to use the `--append-data` or `-D` (capital D) for short, to add data in the following formats:

```shell
npx simple-scaffold ... -D property=value
npx simple-scaffold ... -D property="value with spaces"
npx simple-scaffold ... -D property=value\ with\ spaces
# for raw values (must be JSON supported)
npx simple-scaffold ... -D property:=2345 
```
